<?php

namespace Magecom\AroundProducts\Ui\DataProvider\Product\Around;

use \Magento\Catalog\Ui\DataProvider\Product\Related\AbstractDataProvider;

/**
 * Class AroundDataProvider
 */
class AroundDataProvider extends AbstractDataProvider
{

    public function getData()
    {
        return parent::getData(); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    protected function getLinkType()
    {
        return 'around';
    }
}
