<?php
/**
 * Magecom
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to info@magecom.net so we can send you a copy immediately.
 *
 * @category Magecom
 * @package Magecom_Module
 * @copyright Copyright (c) 2017 Magecom, Inc. (http://www.magecom.net)
 * @license  http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Magecom\AroundProducts\Ui\Component;


use Magento\Framework\Api\FilterBuilder;
use Magento\Framework\Api\Search\ReportingInterface;
use Magento\Framework\Api\Search\SearchCriteriaBuilder;
use Magento\Framework\App\RequestInterface;
use Magento\Framework\ObjectManager\ObjectManager;

/**
 * Class DataProvider
 * @package Magecom\Brand\Ui\Component
 */
class DataProvider extends \Magento\Framework\View\Element\UiComponent\DataProvider\DataProvider
{
    /**
     * @var \Magecom\Brand\Model\ResourceModel\Brand\Collection
     */
    protected $aroundProductsCollection;
    protected $productRepository;
    protected $objectManager;
    protected $_aliasIndex = 1;
    public function __construct(
        $name,
        $primaryFieldName,
        $requestFieldName,
        ReportingInterface $reporting,
        SearchCriteriaBuilder $searchCriteriaBuilder,
        RequestInterface $request,
        FilterBuilder $filterBuilder,
        \Magecom\AroundProducts\Model\ResourceModel\AroundProducts\CollectionFactory $collectionFactory,
        \Magento\Framework\ObjectManager\ObjectManager $objectManager,
        \Magento\Catalog\Api\ProductRepositoryInterface $productRepository,
        \Magento\Eav\Model\Config $config,
        \Magento\Eav\Model\Attribute $attribute,
        array $meta = [],
        array $data = []
    ) {
        $collection = $collectionFactory->create();
        $this->aroundProductsCollection = $collection;
        $this->productRepository = $productRepository;
        parent::__construct(
            $name,
            $primaryFieldName,
            $requestFieldName,
            $reporting,
            $searchCriteriaBuilder,
            $request,
            $filterBuilder,
            $meta,
            $data
        );
    }



    public function addFilter(\Magento\Framework\Api\Filter $filter)
    {
        parent::addFilter($filter); // TODO: Change the autogenerated stub
    }

    /**
     * @param $field
     * @param null $alias
     */
    public function addField($field, $alias = null)
    {

    }
    public function getData()
    {
        return parent::getData(); // TODO: Change the autogenerated stub
    }

}